### ISSUE TITLE
BotMethodInvalidError

### ISSUE THREAD

**Issue by iLaoDi** [snow922841/telegram_channel_downloader#12]
2020-09-24 12:59:38,326 - telethon.client.updates - ERROR - Unhandled exception on handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/telethon/client/updates.py", line 443, in _dispatch_update
    await callback(event)
  File "tg_channel_downloader.py", line 163, in handler
    async for message in client.iter_messages(entity, offset_id=offset_id, reverse=True, limit=None):
  File "/usr/local/lib/python3.7/site-packages/telethon/requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "/usr/local/lib/python3.7/site-packages/telethon/client/messages.py", line 165, in _load_next_chunk
    r = await self.client(self.request)
  File "/usr/local/lib/python3.7/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.7/site-packages/telethon/client/users.py", line 77, in _call
    result = await future
telethon.errors.rpcerrorlist.BotMethodInvalidError: The API access for bot users is restricted. The method you tried to invoke cannot be executed as a bot (caused by GetHistoryRequest)

**Comment by iLaoDi** [comment]
donwload_all_chat = True

然后/start 频道链接 0 就报这个. 
PS: 我把机器人加入到自己频道也报这个,但后续文件可以正常下载.

**Comment by snow922841** [comment]
最开始输入手机号的时候你输入的是bot token吧

**Comment by iLaoDi** [comment]
> 最开始输入手机号的时候你输入的是bot token吧

是的...

**Comment by iLaoDi** [comment]
输入手机号和验证码 就好了
