### ISSUE TITLE
运行报错了

### ISSUE THREAD

**Issue by greatpp95** [snow922841/telegram_channel_downloader#25]
2021-01-13 06:17:34,914 - telethon.client.updates - ERROR - Unhandled exception on handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/updates.py", line 451, in _dispatch_update
    await callback(event)
  File "tg_channel_downloader.py", line 166, in handler
    async for message in client.iter_messages(entity, offset_id=offset_id, reverse=True, limit=None):
  File "/usr/local/lib/python3.7/dist-packages/telethon/requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/messages.py", line 176, in _load_next_chunk
    r = await self.client(self.request)
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/users.py", line 79, in _call
    result = await future
telethon.errors.rpcerrorlist.BotMethodInvalidError: The API access for bot users is restricted. The method you tried to invoke cannot be executed as a bot (caused by SearchRequest)

**Comment by snow922841** [comment]
你输入的是bot的token，需要输入你的手机号
