### ISSUE TITLE
连接超时怎么办呢

### ISSUE THREAD

**Issue by uncle2** [snow922841/telegram_channel_downloader#40]
请教下，要改的字段都改了，是哪里不对呢
PS D:\telegram_channel_downloader-master> python tg_channel_downloader.py
2021-05-12 23:28:46,769 - telethon.network.mtprotosender - WARNING - Attempt 1 at connecting failed: TimeoutError:
2021-05-12 23:28:57,782 - telethon.network.mtprotosender - WARNING - Attempt 2 at connecting failed: TimeoutError:
2021-05-12 23:29:08,799 - telethon.network.mtprotosender - WARNING - Attempt 3 at connecting failed: TimeoutError:
2021-05-12 23:29:19,810 - telethon.network.mtprotosender - WARNING - Attempt 4 at connecting failed: TimeoutError:
2021-05-12 23:29:30,836 - telethon.network.mtprotosender - WARNING - Attempt 5 at connecting failed: TimeoutError:
2021-05-12 23:29:41,855 - telethon.network.mtprotosender - WARNING - Attempt 6 at connecting failed: TimeoutError:
Traceback (most recent call last):
  File "D:\telegram_channel_downloader-master\tg_channel_downloader.py", line 261, in <module>
    bot = TelegramClient('telegram_channel_downloader_bot',
  File "D:\python3964\lib\site-packages\telethon\client\auth.py", line 133, in start
    else self.loop.run_until_complete(coro)
  File "D:\python3964\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\python3964\lib\site-packages\telethon\client\auth.py", line 140, in _start
    await self.connect()
  File "D:\python3964\lib\site-packages\telethon\client\telegrambaseclient.py", line 513, in connect
    if not await self._sender.connect(self._connection(
  File "D:\python3964\lib\site-packages\telethon\network\mtprotosender.py", line 127, in connect
    await self._connect()
  File "D:\python3964\lib\site-packages\telethon\network\mtprotosender.py", line 253, in _connect
    raise ConnectionError('Connection to Telegram failed {} time(s)'.format(self._retries))
ConnectionError: Connection to Telegram failed 5 time(s)

**Comment by uncle2** [comment]
找到问题了，应该是代理的问题，谢谢大佬。

**Comment by snow922841** [comment]
建议放在国外的服务器运行本脚本（俄罗斯好像也把电报屏蔽了。）
