### ISSUE TITLE
链接成功但无法下载

### ISSUE THREAD

**Issue by zzzqu** [snow922841/telegram_channel_downloader#41]
2021-05-24 03:41:33 - 开始下载：🔍🔍🔍sssoou🇨🇳资源搜索(1286693350) - 0
2021-05-24 03:41:33,677 - telethon.client.updates - ERROR - Unhandled exception on handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telethon/client/updates.py", line 454, in _dispatch_update
    await callback(event)
  File "tg_channel_downloader.py", line 166, in handler
    async for message in client.iter_messages(entity, offset_id=offset_id, reverse=True, limit=None):
  File "/usr/local/lib/python3.6/dist-packages/telethon/requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "/usr/local/lib/python3.6/dist-packages/telethon/client/messages.py", line 178, in _load_next_chunk
    r = await self.client(self.request)
  File "/usr/local/lib/python3.6/dist-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.6/dist-packages/telethon/client/users.py", line 79, in _call
    result = await future
telethon.errors.rpcerrorlist.BotMethodInvalidError: The API access for bot users is restricted. The method you tried to invoke cannot be executed as a bot (caused by GetHistoryRequest)

**Comment by snow922841** [comment]
> 2021-05-24 03:41:33 - 开始下载：🔍🔍🔍sssoou🇨🇳资源搜索(1286693350) - 0
> 
> 2021-05-24 03:41:33,677 - telethon.client.updates - ERROR - Unhandled exception on handler
> 
> Traceback (most recent call last):
> 
>   File "/usr/local/lib/python3.6/dist-packages/telethon/client/updates.py", line 454, in _dispatch_update
> 
>     await callback(event)
> 
>   File "tg_channel_downloader.py", line 166, in handler
> 
>     async for message in client.iter_messages(entity, offset_id=offset_id, reverse=True, limit=None):
> 
>   File "/usr/local/lib/python3.6/dist-packages/telethon/requestiter.py", line 74, in __anext__
> 
>     if await self._load_next_chunk():
> 
>   File "/usr/local/lib/python3.6/dist-packages/telethon/client/messages.py", line 178, in _load_next_chunk
> 
>     r = await self.client(self.request)
> 
>   File "/usr/local/lib/python3.6/dist-packages/telethon/client/users.py", line 30, in __call__
> 
>     return await self._call(self._sender, request, ordered=ordered)
> 
>   File "/usr/local/lib/python3.6/dist-packages/telethon/client/users.py", line 79, in _call
> 
>     result = await future
> 
> telethon.errors.rpcerrorlist.BotMethodInvalidError: The API access for bot users is restricted. The method you tried to invoke cannot be executed as a bot (caused by GetHistoryRequest)
> 
> 

登录的时候需要输入手机号登录，如果使用bot登录，权限会不够报错
