### ISSUE TITLE
监控全部频道出错

### ISSUE THREAD

**Issue by zzzqu** [snow922841/telegram_channel_downloader#42]
python3 tg_channel_downloader.py
Successfully started (Press Ctrl+C to stop)
2021-05-28 03:08:28,458 - telethon.client.updates - ERROR - Unhandled exception on all_chat_download
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telethon/client/updates.py", line 454, in _dispatch_update
    await callback(event)
  File "tg_channel_downloader.py", line 210, in all_chat_download
    chat_title = entity.title

怎么解决呢

**Comment by snow922841** [comment]
可能遇到频道名称无法解析的情况

**Comment by snow922841** [comment]
如果问题没有解决请重新开启Issues
