### ISSUE TITLE
一直连接失败

### ISSUE THREAD

**Issue by ttlvip** [snow922841/telegram_channel_downloader#59]
启动报错：
F:\Workspace\Applications\telegram_channel_downloader\venv\Scripts\python.exe F:/Workspace/Applications/telegram_channel_downloader/tg_channel_downloader.py
2021-09-11 13:46:17,546 - telethon.network.mtprotosender - WARNING - Attempt 1 at connecting failed: TimeoutError: 
2021-09-11 13:46:28,567 - telethon.network.mtprotosender - WARNING - Attempt 2 at connecting failed: TimeoutError: 
2021-09-11 13:46:39,579 - telethon.network.mtprotosender - WARNING - Attempt 3 at connecting failed: TimeoutError: 
2021-09-11 13:46:50,597 - telethon.network.mtprotosender - WARNING - Attempt 4 at connecting failed: TimeoutError: 
2021-09-11 13:47:01,616 - telethon.network.mtprotosender - WARNING - Attempt 5 at connecting failed: TimeoutError: 
2021-09-11 13:47:12,629 - telethon.network.mtprotosender - WARNING - Attempt 6 at connecting failed: TimeoutError: 
Traceback (most recent call last):
  File "F:\Workspace\Applications\telegram_channel_downloader\tg_channel_downloader.py", line 277, in <module>
    bot = TelegramClient('telegram_channel_downloader_bot',
  File "F:\Workspace\Applications\telegram_channel_downloader\venv\lib\site-packages\telethon\client\auth.py", line 133, in start
    else self.loop.run_until_complete(coro)
  File "C:\Users\tlafa\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "F:\Workspace\Applications\telegram_channel_downloader\venv\lib\site-packages\telethon\client\auth.py", line 140, in _start
    await self.connect()
  File "F:\Workspace\Applications\telegram_channel_downloader\venv\lib\site-packages\telethon\client\telegrambaseclient.py", line 513, in connect
    if not await self._sender.connect(self._connection(
  File "F:\Workspace\Applications\telegram_channel_downloader\venv\lib\site-packages\telethon\network\mtprotosender.py", line 127, in connect
    await self._connect()
  File "F:\Workspace\Applications\telegram_channel_downloader\venv\lib\site-packages\telethon\network\mtprotosender.py", line 253, in _connect
    raise ConnectionError('Connection to Telegram failed {} time(s)'.format(self._retries))
ConnectionError: Connection to Telegram failed 5 time(s)
=================================================================================
打开全局代理仍然报错

**Comment by ttlvip** [comment]
直接双击运行tg_channel_downloader.py 可以正常使用了。
