### ISSUE TITLE
python参数都设置好了，但是运行好多报错啊，大佬看看是怎么回事。

### ISSUE THREAD

**Issue by jiarandiana010** [snow922841/telegram_channel_downloader#66]
不知道是不是因为我装的是python3.9所以不兼容，然后最后一段还说自己建的bot受限制了。
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/telethon/client/updates.py", line 467, in _dispatch_update
    await callback(event)
  File "/Users/XXX/telegram_channel_downloader/tg_channel_downloader.py", line 183, in handler
    async for message in client.iter_messages(entity, offset_id=offset_id, reverse=True, limit=None):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/telethon/requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/telethon/client/messages.py", line 184, in _load_next_chunk
    r = await self.client(self.request)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/telethon/client/users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.BotMethodInvalidError: The API access for bot users is restricted. The method you tried to invoke cannot be executed as a bot (caused by GetHistoryRequest)

**Comment by jiarandiana010** [comment]
OK，看问题贴解决了，之所以错误是因为开头输入的是bot的数据而不是手机号。

**Comment by snow922841** [comment]
好多人输入的是bot的token出现问题
