### ISSUE TITLE
报错 无法下载 TypeError: object NoneType can't be used in 'await' expression

### ISSUE THREAD

**Issue by silenvps20** [snow922841/telegram_channel_downloader#7]
尝试下载某个频道的视频，遇到报错：

root@debian:~/telegram_channel_downloader# python3 tg_channel_downloader.py
TgCrypto is missing! Pyrogram will work the same, but at a much slower speed. More info: https://docs.pyrogram.org/topics/tgcrypto
Pyrogram v1.0.2, Copyright (C) 2017-2020 Dan <https://github.com/delivrance>
Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

Downloading: 7--********.mp4:   1%|▎                                      | 1.05M/132M [00:14<29:55, 72.9kB/s]ERROR:pyrogram.client:object NoneType can't be used in 'await' expression
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/client.py", line 956, in get_file
    *progress_args
TypeError: object NoneType can't be used in 'await' expression
Downloading: 7--**********.mp4:   1%|▎                                      | 1.05M/132M [00:14<29:55, 72.9kB/s]
Downloading: 8--************.mp4:   4%| | 1.05M/25.2M [00:14<05:31, 72.9kB/sERROR:pyrogram.client:object NoneType can't be used in 'await' expression
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/client.py", line 956, in get_file
    *progress_args
TypeError: object NoneType can't be used in 'await' expression
Downloading: 8--*************.mp4:   4%| | 1.05M/25.2M [00:14<05:31, 72.9kB/s
Downloading: 10--*******.mp4:   0%|                                                    | 0.00/8.48M [00:00<?, ?B/s]^CTraceback (most recent call last):
  File "tg_channel_downloader.py", line 140, in <module>
    main()
  File "tg_channel_downloader.py", line 97, in main
    message.download(file_name=os.path.join(file_save_path, file_name), progress=td.my_update)
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/sync.py", line 51, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/session/session.py", line 348, in network_worker
    packet = await self.connection.recv()
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/connection/connection.py", line 83, in recv
    return await self.protocol.recv()
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/connection/transport/tcp/tcp_abridged_o.py", line 90, in recv
    return aes.ctr256_decrypt(data, *self.decrypt)
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/crypto/aes.py", line 74, in ctr256_decrypt
    return ctr(data, key, iv, state or bytearray(1))
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/crypto/aes.py", line 128, in ctr
    chunk = cipher.encrypt(iv)
  File "/usr/local/lib/python3.7/dist-packages/pyaes/aes.py", line 222, in encrypt
    self.T4[ t[(i + s3) % 4]        & 0xFF] ^
KeyboardInterrupt
root@debian:~/telegram_channel_downloader#

**Comment by snow922841** [comment]
试一下pip3 install -U tgcrypto

silenvps20 <notifications@github.com>于2020年8月27日 周四11:39写道：

**Comment by silenvps20** [comment]
@snow922841 
依然报错，运行后一直弹出下载新的视频，但是每一个视频都没有下载成功，下载目录里只有空的日期文件夹

Downloading: 160--*********.mp4:   0%|                           | 1.05M/387M [00:01<06:09, 1.04MB/s]
Downloading: 161--*********.mp4:   0%|▏                                | 1.05M/246M [00:01<03:56, 1.03MB/s]ERROR:pyrogram.client:object NoneType can't be used in 'await' expression
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/client.py", line 956, in get_file
    *progress_args
TypeError: object NoneType can't be used in 'await' expression
Downloading: 161--*********.mp4:   0%|▏                                | 1.05M/246M [00:01<03:57, 1.03MB/s]
Downloading: 162--*********A.mp4:   0%|                                    | 1.05M/1.42G [00:01<22:42, 1.04MB/s]ERROR:pyrogram.client:object NoneType can't be used in 'await' expression
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/client.py", line 956, in get_file
    *progress_args
TypeError: object NoneType can't be used in 'await' expression
Downloading: 162--*******A.mp4:   0%|                                    | 1.05M/1.42G [00:01<22:43, 1.04MB/s]
Downloading: 163--*******.mp4:   0%|                                                        | 0.00/263M [00:00<?, ?B/s]^CTraceback (most recent call last):
  File "tg_channel_downloader.py", line 140, in <module>
    main()
  File "tg_channel_downloader.py", line 97, in main
    message.download(file_name=os.path.join(file_save_path, file_name), progress=td.my_update)
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/sync.py", line 51, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

**Comment by snow922841** [comment]
这样吧，你把频道说一下，我去试试看

silenvps20 <notifications@github.com>于2020年8月27日 周四11:56写道：

**Comment by silenvps20** [comment]
@snow922841 注意频道内容为 #NSFW 不要在公共场合打开  https://t.me/pornhubjingxuan

**Comment by snow922841** [comment]
那我也不太懂了。我win10测试正常下载···

Pyrogram v0.18.0, Copyright (C) 2017-2020 Dan <https://github.com/delivrance>
Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

Downloading: 292--复旦大学露出.mp4: 100%|██████████| 248M/248M [00:48<00:00, 5.13MB/s]
Downloading: 291--花臂少女的性爱生活.mp4: 100%|██████████| 107M/107M [00:20<00:00, 5.33MB/s]
Downloading: 290--.mp4: 100%|██████████| 40.5M/40.5M [00:07<00:00, 5.68MB/s]
Downloading: 289--.mp4: 100%|██████████| 268M/268M [00:50<00:00, 5.26MB/s]

**Comment by snow922841** [comment]
> @snow922841 注意频道内容为 #NSFW 不要在公共场合打开 https://t.me/pornhubjingxuan

会不会是没有读写权限？

**Comment by silenvps20** [comment]
已经给了755权限 @snow922841

**Comment by silenvps20** [comment]
@snow922841 debian 和Ubuntu 系统都试过了

**Comment by snow922841** [comment]
> @snow922841 debian 和Ubuntu 系统都试过了

其实我自己在Ubuntu测试也是不能运行，等晚上回去看能不能解决，

**Comment by silenvps20** [comment]
好的 多谢大佬 @snow922841

**Comment by snow922841** [comment]
已经对脚本进行重构。欢迎测试，有问题可以直接提issue

**Comment by silenvps20** [comment]
正在测试，可以下载，不过速度基本在1M/s一下
服务器是OP法国杜甫，debian10

**Comment by snow922841** [comment]
我也一样很慢，荷兰gcp 大概一点三，应该是telethon调用的解密库的问题，目前还没有办法，后面看加个多线程吧

silenvps20 <notifications@github.com>于2020年8月30日 周日19:47写道：

**Comment by silenvps20** [comment]
期待多线程

**Comment by silenvps20** [comment]
在下载到第75个视频时，遇到错误：

Traceback (most recent call last):
  File "tg_channel_downloader.py", line 181, in <module>
    client.loop.run_until_complete(main())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "tg_channel_downloader.py", line 135, in main
    progress_callback=td.my_update)
  File "/usr/local/lib/python3.7/dist-packages/telethon/tl/custom/message.py", line 764, in download_media
    return await self._client.download_media(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/downloads.py", line 368, in download_media
    media, file, date, thumb, progress_callback
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/downloads.py", line 780, in _download_document
    progress_callback=progress_callback
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/downloads.py", line 468, in download_file
    input_location, request_size=part_size, dc_id=dc_id):
  File "/usr/local/lib/python3.7/dist-packages/telethon/requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/downloads.py", line 61, in _load_next_chunk
    cur = await self._request()
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/downloads.py", line 71, in _request
    result = await self.client._call(self._sender, self.request)
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/users.py", line 77, in _call
    result = await future
telethon.errors.rpcerrorlist.FileReferenceExpiredError: The file reference has expired and is no longer valid or it belongs to self-destructing media and cannot be resent (caused by GetFileRequest)

之后脚本跳过了此视频继续下载

**Comment by snow922841** [comment]
目前是有这样的情况，这个异常我还在想办法捕获，其实重新请求一次就OK了，

silenvps20 <notifications@github.com>于2020年8月30日 周日23:45写道：

**Comment by silenvps20** [comment]
似乎大于1G的视频会无法下载，尝试过数次重新下载，都不成功，脚本在一段时间后会自动停止。

手动重新运行脚本后，下载速度极慢，保持在30KB/s上下，如果手动停止脚本，会提示如下错误：

Traceback (most recent call last):
  File "tg_channel_downloader.py", line 181, in <module>
    client.loop.run_until_complete(main())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

**Comment by snow922841** [comment]
更新一下脚本试试，看一下说明和配置区域的注释。
