### ISSUE TITLE
全部都配置好了但是还是错误，求大佬帮助，试了几个频道都有些问题

### ISSUE THREAD

**Issue by xiaohei-14** [snow922841/telegram_channel_downloader#81]
File "/usr/local/lib/python3.9/dist-packages/telethon/client/updates.py", line 467, in _dispatch_update
    await callback(event)
  File "/root/telegram_channel_downloader/tg_channel_downloader.py", line 151, in handler
    channel_id = text[1].split('/')[4]
IndexError: list index out of range
2022-03-12 08:46:31,958 - telethon.client.updates - ERROR - Unhandled exception on handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/updates.py", line 467, in _dispatch_update
    await callback(event)
  File "/root/telegram_channel_downloader/tg_channel_downloader.py", line 162, in handler
    offset_id = int(text[2])
ValueError: invalid literal for int() with base 10: '\nhttps://telegra.ph/dfgdfgdgdfg'
2022-03-12 08:47:17,173 - telethon.client.updates - ERROR - Unhandled exception on handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/updates.py", line 467, in _dispatch_update
    await callback(event)
  File "/root/telegram_channel_downloader/tg_channel_downloader.py", line 162, in handler
    offset_id = int(text[2])
ValueError: invalid literal for int() with base 10: 'https://t.me/jisdfsdfsdfs6'

**### 报错就是如上面，我这里用的是python3.9，Debian11的系统**

**Comment by xiaohei-14** [comment]
了解到问题所在了我填写的是bot_token，不是用的手机号验证，但是怎么改过来，就是重新运行python3 tg_channel_downloader.py时没有显示让我填电话号码验证，就直接成功了，应该还是bot_token在起作用，请问大佬如何做。

**Comment by hello1983** [comment]
我也是这样的错误。

**Comment by insoxin** [comment]
> 了解到问题所在了我填写的是bot_token，不是用的手机号验证，但是怎么改过来，就是重新运行python3 tg_channel_downloader.py时没有显示让我填电话号码验证，就直接成功了，应该还是bot_token在起作用，请问大佬如何做。



> 我也是这样的错误。

我也遇到了相同的错误但不是这个项目 python3.10

**Comment by ljhOfGithub** [comment]
> 

把session文件删了重新用python跑

**Comment by ljhOfGithub** [comment]
> File "/usr/local/lib/python3.9/dist-packages/telethon/client/updates.py", line 467, in _dispatch_update await callback(event) File "/root/telegram_channel_downloader/tg_channel_downloader.py", line 151, in handler channel_id = text[1].split('/')[4] IndexError: list index out of range 2022-03-12 08:46:31,958 - telethon.client.updates - ERROR - Unhandled exception on handler Traceback (most recent call last): File "/usr/local/lib/python3.9/dist-packages/telethon/client/updates.py", line 467, in _dispatch_update await callback(event) File "/root/telegram_channel_downloader/tg_channel_downloader.py", line 162, in handler offset_id = int(text[2]) ValueError: invalid literal for int() with base 10: '\nhttps://telegra.ph/dfgdfgdgdfg' 2022-03-12 08:47:17,173 - telethon.client.updates - ERROR - Unhandled exception on handler Traceback (most recent call last): File "/usr/local/lib/python3.9/dist-packages/telethon/client/updates.py", line 467, in _dispatch_update await callback(event) File "/root/telegram_channel_downloader/tg_channel_downloader.py", line 162, in handler offset_id = int(text[2]) ValueError: invalid literal for int() with base 10: 'https://t.me/jisdfsdfsdfs6'
> 
> **### 报错就是如上面，我这里用的是python3.9，Debian11的系统**

把session文件删了重新用python跑
